<a href="https://colab.research.google.com/github/rayan239/100_days_ML/blob/main/Hyperparameter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/content/diabetes.csv")

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [6]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [8]:
x = scaler.fit_transform(x)

In [9]:
x.shape

(768, 8)

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [44]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [12]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
model.fit(x_train, y_train, batch_size=31, epochs=100, validation_data=(x_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.5554 - loss: 0.6931 - val_accuracy: 0.6429 - val_loss: 0.6778
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6348 - val_accuracy: 0.7338 - val_loss: 0.6225
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.5944 - val_accuracy: 0.7922 - val_loss: 0.5812
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5642 - val_accuracy: 0.7987 - val_loss: 0.5511
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5410 - val_accuracy: 0.7987 - val_loss: 0.5278
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5239 - val_accuracy: 0.8052 - val_loss: 0.5090
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7638 - loss: 0.5102 - val_accuracy: 0.7987 - val_loss: 0.4954
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7687 - loss: 0.4992 - val_accuracy: 0.7987 - val_loss: 0.4841
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7752 - loss: 0.4906 - val_accuracy: 0.7987 - val_loss: 0.4761
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7769 - loss: 0.4837 - val_accuracy: 0.8052 - val_loss: 0.4695
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7834 - loss: 0.4789 - val_accuracy: 0.8182 - val_loss: 0.4648
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7801 - loss: 0.4739 - val_accuracy: 0.8182 - val_loss: 0.4603
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7818 - loss: 0.4704 - val_accuracy: 0.8117 - val_loss: 0.4579
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7850 - loss: 0.4671 - val_accuracy: 0.8052 - val_loss: 0.4561
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7883 - loss: 0.4643 - val_accuracy: 0.8052 - val_loss: 0.4542
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7866 - loss: 0.4621 - val_accuracy: 0.8052 - val_loss: 0.4530
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7883 - loss: 0.4601 - val_accuracy: 0.7987 - val_loss: 0.4530
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7883 - loss: 0.4584 - val_accuracy: 0.7987 - val_loss: 0.4517
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7883 - loss: 0.4570 - val_accuracy: 0.7922 - val_loss: 0.4518
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4553 - val_accuracy: 0.7857 - val_loss: 0.4511
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4540 - val_accuracy: 0.7857 - val_loss: 0.4514
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4529 - val_accuracy: 0.7857 - val_loss: 0.4514
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4520 - val_accuracy: 0.7857 - val_loss: 0.4519
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4510 - val_accuracy: 0.7857 - val_loss: 0.4526
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4495 - val_accuracy: 0.7857 - val_loss: 0.4523
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4491 - val_accuracy: 0.7857 - val_loss: 0.4523
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7801 - loss: 0.4489 - val_accuracy: 0.7857 - val_loss: 0.4529
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4472 - val_accuracy: 0.7857 - val_loss: 0.4526
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4464 - val_accuracy: 0.7922 - val_loss: 0.4526
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4465 - val_accuracy: 0.7922 - val_loss: 0.4526
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4454 - val_accuracy: 0.7987 - val_loss: 0.4533
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4446 - val_accuracy: 0.7922 - val_loss: 0.4526
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4440 - val_accuracy: 0.7922 - val_loss: 0.4532
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4435 - val_accuracy: 0.7922 - val_loss: 0.4535
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4429 - val_accuracy: 0.7922 - val_loss: 0.4527
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4420 - val_accuracy: 0.7922 - val_loss: 0.4538
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4420 - val_accuracy: 0.7922 - val_loss: 0.4533
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4411 - val_accuracy: 0.7922 - val_loss: 0.4549
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4406 - val_accuracy: 0.8052 - val_loss: 0.4551
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4401 - val_accuracy: 0.7922 - val_loss: 0.4549
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4396 - val_accuracy: 0.7987 - val_loss: 0.4551
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4391 - val_accuracy: 0.7922 - val_loss: 0.4540
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4390 - val_accuracy: 0.7857 - val_loss: 0.4556
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4379 - val_accuracy: 0.8052 - val_loss: 0.4556
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4372 - val_accuracy: 0.7987 - val_loss: 0.4551
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4367 - val_accuracy: 0.7987 - val_loss: 0.4549
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4365 - val_accuracy: 0.7987 - val_loss: 0.4554
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4358 - val_accuracy: 0.7792 - val_loss: 0.4554
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4351 - val_accuracy: 0.7857 - val_loss: 0.4561
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4348 - val_accuracy: 0.7857 - val_loss: 0.4561
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7866 - loss: 0.4341 - val_accuracy: 0.7857 - val_loss: 0.4560
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4339 - val_accuracy: 0.7857 - val_loss: 0.4548
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7932 - loss: 0.4333 - val_accuracy: 0.7792 - val_loss: 0.4552
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7883 - loss: 0.4332 - val_accuracy: 0.7792 - val_loss: 0.4551
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7932 - loss: 0.4323 - val_accuracy: 0.7857 - val_loss: 0.4549
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7915 - loss: 0.4320 - val_accuracy: 0.7857 - val_loss: 0.4555
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4315 - val_accuracy: 0.7792 - val_loss: 0.4550
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4312 - val_accuracy: 0.7922 - val_loss: 0.4554
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4313 - val_accuracy: 0.7792 - val_loss: 0.4551
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4301 - val_accuracy: 0.7857 - val_loss: 0.4551
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4296 - val_accuracy: 0.7922 - val_loss: 0.4544
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4294 - val_accuracy: 0.7987 - val_loss: 0.4546
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4290 - val_accuracy: 0.7987 - val_loss: 0.4534
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4283 - val_accuracy: 0.7987 - val_loss: 0.4544
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4283 - val_accuracy: 0.7922 - val_loss: 0.4540
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4283 - val_accuracy: 0.7987 - val_loss: 0.4539
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4275 - val_accuracy: 0.7987 - val_loss: 0.4536
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4271 - val_accuracy: 0.7987 - val_loss: 0.4544
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4269 - val_accuracy: 0.7987 - val_loss: 0.4538
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4263 - val_accuracy: 0.7987 - val_loss: 0.4539
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4263 - val_accuracy: 0.7922 - val_loss: 0.4531
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4256 - val_accuracy: 0.7922 - val_loss: 0.4534
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4254 - val_accuracy: 0.7987 - val_loss: 0.4531
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4252 - val_accuracy: 0.7987 - val_loss: 0.4535
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4243 - val_accuracy: 0.7987 - val_loss: 0.4531
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4241 - val_accuracy: 0.7987 - val_loss: 0.4533
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4241 - val_accuracy: 0.7987 - val_loss: 0.4533
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4239 - val_accuracy: 0.7922 - val_loss: 0.4534
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4231 - val_accuracy: 0.7922 - val_loss: 0.4520
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4230 - val_accuracy: 0.7922 - val_loss: 0.4516
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4225 - val_accuracy: 0.7987 - val_loss: 0.4529
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4221 - val_accuracy: 0.8052 - val_loss: 0.4528
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4220 - val_accuracy: 0.7922 - val_loss: 0.4513
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4222 - val_accuracy: 0.8052 - val_loss: 0.4526
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4214 - val_accuracy: 0.7922 - val_loss: 0.4503
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4213 - val_accuracy: 0.7922 - val_loss: 0.4508
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4207 - val_accuracy: 0.7922 - val_loss: 0.4509
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4204 - val_accuracy: 0.8052 - val_loss: 0.4503
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4200 - val_accuracy: 0.8052 - val_loss: 0.4512
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4192 - val_accuracy: 0.7987 - val_loss: 0.4505
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4193 - val_accuracy: 0.7922 - val_loss: 0.4503
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8062 - loss: 0.4197 - val_accuracy: 0.8052 - val_loss: 0.4516
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4186 - val_accuracy: 0.8052 - val_loss: 0.4501
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4185 - val_accuracy: 0.7987 - val_loss: 0.4495
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4181 - val_accuracy: 0.7987 - val_loss: 0.4498
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4180 - val_accuracy: 0.7987 - val_loss: 0.4507
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4177 - val_accuracy: 0.7987 - val_loss: 0.4497
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8046 - loss: 0.4183 - val_accuracy: 0.7922 - val_loss: 0.4493
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4170 - val_accuracy: 0.8052 - val_loss: 0.4483
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8062 - loss: 0.4167 - val_accuracy: 0.8117 - val_loss: 0.4481

In [14]:
# 1. appropriate optimizer
# 2. no. of nodes
# 3. no. of layers
# 4. all in one model

# 1. appropriate optimizer

In [15]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 2.1 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [16]:
import kerastuner as kt

/tmp/ipykernel_829/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [17]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta'])
  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [18]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=6,
    directory='mydir',
    project_name='optimizer'
)

In [19]:
tuner.search(x_train, y_train, epochs=6, validation_data=(x_test, y_test) )

Trial 4 Complete [00h 00m 03s]
val_accuracy: 0.649350643157959

Best val_accuracy So Far: 0.7662337422370911
Total elapsed time: 00h 00m 22s

In [20]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [21]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.fit(x_train, y_train, batch_size=32, epochs=100,initial_epoch=6, validation_data=(x_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7362 - loss: 0.5242 - val_accuracy: 0.7727 - val_loss: 0.5227
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7362 - loss: 0.5107 - val_accuracy: 0.7597 - val_loss: 0.5144
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5014 - val_accuracy: 0.7727 - val_loss: 0.5086
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7443 - loss: 0.4942 - val_accuracy: 0.7727 - val_loss: 0.5038
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7557 - loss: 0.4880 - val_accuracy: 0.7922 - val_loss: 0.4999
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4830 - val_accuracy: 0.7857 - val_loss: 0.4975
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4789 - val_accuracy: 0.7857 - val_loss: 0.4942
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4751 - val_accuracy: 0.7922 - val_loss: 0.4920
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7704 - loss: 0.4715 - val_accuracy: 0.7857 - val_loss: 0.4900
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7720 - loss: 0.4691 - val_accuracy: 0.7987 - val_loss: 0.4883
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7801 - loss: 0.4670 - val_accuracy: 0.8052 - val_loss: 0.4860
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7769 - loss: 0.4646 - val_accuracy: 0.8052 - val_loss: 0.4858
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7671 - loss: 0.4629 - val_accuracy: 0.7987 - val_loss: 0.4852
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7704 - loss: 0.4612 - val_accuracy: 0.7922 - val_loss: 0.4842
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7720 - loss: 0.4598 - val_accuracy: 0.8052 - val_loss: 0.4839
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7687 - loss: 0.4587 - val_accuracy: 0.7987 - val_loss: 0.4834
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7704 - loss: 0.4575 - val_accuracy: 0.7922 - val_loss: 0.4838
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7704 - loss: 0.4562 - val_accuracy: 0.7922 - val_loss: 0.4842
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7769 - loss: 0.4555 - val_accuracy: 0.7922 - val_loss: 0.4847
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.7785 - loss: 0.4541 - val_accuracy: 0.7922 - val_loss: 0.4844
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7785 - loss: 0.4534 - val_accuracy: 0.7922 - val_loss: 0.4847
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.7736 - loss: 0.4527 - val_accuracy: 0.7922 - val_loss: 0.4851
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7834 - loss: 0.4516 - val_accuracy: 0.7922 - val_loss: 0.4846
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7752 - loss: 0.4510 - val_accuracy: 0.7792 - val_loss: 0.4836
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7801 - loss: 0.4499 - val_accuracy: 0.7857 - val_loss: 0.4835
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7801 - loss: 0.4494 - val_accuracy: 0.7922 - val_loss: 0.4825
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7785 - loss: 0.4487 - val_accuracy: 0.7857 - val_loss: 0.4831
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7818 - loss: 0.4479 - val_accuracy: 0.7922 - val_loss: 0.4828
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7769 - loss: 0.4477 - val_accuracy: 0.7857 - val_loss: 0.4827
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7769 - loss: 0.4466 - val_accuracy: 0.7857 - val_loss: 0.4842
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7818 - loss: 0.4461 - val_accuracy: 0.7857 - val_loss: 0.4835
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7866 - loss: 0.4459 - val_accuracy: 0.7857 - val_loss: 0.4838
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7834 - loss: 0.4450 - val_accuracy: 0.7857 - val_loss: 0.4836
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4446 - val_accuracy: 0.7857 - val_loss: 0.4831
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4442 - val_accuracy: 0.7857 - val_loss: 0.4833
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4436 - val_accuracy: 0.7857 - val_loss: 0.4840
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4430 - val_accuracy: 0.7727 - val_loss: 0.4849
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7866 - loss: 0.4427 - val_accuracy: 0.7792 - val_loss: 0.4841
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4422 - val_accuracy: 0.7727 - val_loss: 0.4839
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4416 - val_accuracy: 0.7792 - val_loss: 0.4842
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4412 - val_accuracy: 0.7792 - val_loss: 0.4840
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4408 - val_accuracy: 0.7792 - val_loss: 0.4831
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4403 - val_accuracy: 0.7792 - val_loss: 0.4824
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4397 - val_accuracy: 0.7792 - val_loss: 0.4816
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4395 - val_accuracy: 0.7792 - val_loss: 0.4819
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4390 - val_accuracy: 0.7792 - val_loss: 0.4810
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4382 - val_accuracy: 0.7792 - val_loss: 0.4802
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4383 - val_accuracy: 0.7792 - val_loss: 0.4805
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4377 - val_accuracy: 0.7792 - val_loss: 0.4811
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4371 - val_accuracy: 0.7792 - val_loss: 0.4818
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4373 - val_accuracy: 0.7792 - val_loss: 0.4815
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4363 - val_accuracy: 0.7792 - val_loss: 0.4813
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4359 - val_accuracy: 0.7792 - val_loss: 0.4797
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4358 - val_accuracy: 0.7792 - val_loss: 0.4797
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4355 - val_accuracy: 0.7792 - val_loss: 0.4808
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4349 - val_accuracy: 0.7792 - val_loss: 0.4802
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4345 - val_accuracy: 0.7792 - val_loss: 0.4809
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4343 - val_accuracy: 0.7857 - val_loss: 0.4811
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4339 - val_accuracy: 0.7857 - val_loss: 0.4818
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7866 - loss: 0.4336 - val_accuracy: 0.7857 - val_loss: 0.4812
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4331 - val_accuracy: 0.7857 - val_loss: 0.4810
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4329 - val_accuracy: 0.7857 - val_loss: 0.4806
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4326 - val_accuracy: 0.7857 - val_loss: 0.4809
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4321 - val_accuracy: 0.7792 - val_loss: 0.4815
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4316 - val_accuracy: 0.7792 - val_loss: 0.4815
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4313 - val_accuracy: 0.7792 - val_loss: 0.4816
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4309 - val_accuracy: 0.7792 - val_loss: 0.4816
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4306 - val_accuracy: 0.7857 - val_loss: 0.4812
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4302 - val_accuracy: 0.7857 - val_loss: 0.4808
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4297 - val_accuracy: 0.7857 - val_loss: 0.4813
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4292 - val_accuracy: 0.7857 - val_loss: 0.4812
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4293 - val_accuracy: 0.7792 - val_loss: 0.4821
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4289 - val_accuracy: 0.7857 - val_loss: 0.4807
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4288 - val_accuracy: 0.7922 - val_loss: 0.4811
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4281 - val_accuracy: 0.7922 - val_loss: 0.4810
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4277 - val_accuracy: 0.7922 - val_loss: 0.4809
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4272 - val_accuracy: 0.7922 - val_loss: 0.4814
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4274 - val_accuracy: 0.7922 - val_loss: 0.4814
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4268 - val_accuracy: 0.7922 - val_loss: 0.4813
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4262 - val_accuracy: 0.7922 - val_loss: 0.4819
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4259 - val_accuracy: 0.7922 - val_loss: 0.4820
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4257 - val_accuracy: 0.7922 - val_loss: 0.4818
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4255 - val_accuracy: 0.7922 - val_loss: 0.4819
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4252 - val_accuracy: 0.7922 - val_loss: 0.4827
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4252 - val_accuracy: 0.7922 - val_loss: 0.4829
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4244 - val_accuracy: 0.7922 - val_loss: 0.4822
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4240 - val_accuracy: 0.8052 - val_loss: 0.4829
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4239 - val_accuracy: 0.8052 - val_loss: 0.4824
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4233 - val_accuracy: 0.7922 - val_loss: 0.4821
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4235 - val_accuracy: 0.7922 - val_loss: 0.4816
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4227 - val_accuracy: 0.7987 - val_loss: 0.4818
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4226 - val_accuracy: 0.7987 - val_loss: 0.4816
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4225 - val_accuracy: 0.7987 - val_loss: 0.4816
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4219 - val_accuracy: 0.7987 - val_loss: 0.4823

# 2. no. of nodes

In [24]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('units', min_value=8, max_value=128, step=1)
  model.add(Dense(units=units, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [25]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='mydir',
    project_name='number_of_nodes'
)

In [26]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.8051947951316833

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 12s

In [27]:
tuner.get_best_hyperparameters()[0].values

{'units': 112}

In [28]:
model = tuner.get_best_models(num_models=1)[0]

In [29]:
model.fit(x_train, y_train, batch_size=32, epochs=100, initial_epoch=5, validation_data=(x_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7655 - loss: 0.4902 - val_accuracy: 0.8052 - val_loss: 0.4793
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4746 - val_accuracy: 0.8052 - val_loss: 0.4717
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4678 - val_accuracy: 0.8182 - val_loss: 0.4683
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4626 - val_accuracy: 0.8052 - val_loss: 0.4681
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4594 - val_accuracy: 0.7987 - val_loss: 0.4654
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4567 - val_accuracy: 0.8052 - val_loss: 0.4660
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4543 - val_accuracy: 0.7987 - val_loss: 0.4654
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4527 - val_accuracy: 0.7987 - val_loss: 0.4649
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4507 - val_accuracy: 0.8052 - val_loss: 0.4657
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4489 - val_accuracy: 0.7987 - val_loss: 0.4668
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4475 - val_accuracy: 0.7922 - val_loss: 0.4660
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4467 - val_accuracy: 0.7922 - val_loss: 0.4666
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4442 - val_accuracy: 0.7922 - val_loss: 0.4677
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4438 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4421 - val_accuracy: 0.8117 - val_loss: 0.4660
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4416 - val_accuracy: 0.8117 - val_loss: 0.4655
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4403 - val_accuracy: 0.8117 - val_loss: 0.4651
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4402 - val_accuracy: 0.8117 - val_loss: 0.4632
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4376 - val_accuracy: 0.8182 - val_loss: 0.4636
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4371 - val_accuracy: 0.8117 - val_loss: 0.4613
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4362 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4364 - val_accuracy: 0.8052 - val_loss: 0.4618
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4343 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4335 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4325 - val_accuracy: 0.7987 - val_loss: 0.4612
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4330 - val_accuracy: 0.8052 - val_loss: 0.4601
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4307 - val_accuracy: 0.8117 - val_loss: 0.4605
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4305 - val_accuracy: 0.8117 - val_loss: 0.4600
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4295 - val_accuracy: 0.8052 - val_loss: 0.4626
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4278 - val_accuracy: 0.8117 - val_loss: 0.4604
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4282 - val_accuracy: 0.8117 - val_loss: 0.4604
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4270 - val_accuracy: 0.8182 - val_loss: 0.4603
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4263 - val_accuracy: 0.8182 - val_loss: 0.4592
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4259 - val_accuracy: 0.8117 - val_loss: 0.4598
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4243 - val_accuracy: 0.8117 - val_loss: 0.4612
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4236 - val_accuracy: 0.8117 - val_loss: 0.4595
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.4599
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4225 - val_accuracy: 0.8117 - val_loss: 0.4618
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7948 - loss: 0.4222 - val_accuracy: 0.8117 - val_loss: 0.4587
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7964 - loss: 0.4212 - val_accuracy: 0.8182 - val_loss: 0.4569
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7980 - loss: 0.4201 - val_accuracy: 0.8117 - val_loss: 0.4574
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4198 - val_accuracy: 0.8052 - val_loss: 0.4581
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4187 - val_accuracy: 0.8117 - val_loss: 0.4600
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4186 - val_accuracy: 0.8052 - val_loss: 0.4590
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4183 - val_accuracy: 0.8052 - val_loss: 0.4588
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4171 - val_accuracy: 0.8052 - val_loss: 0.4588
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4164 - val_accuracy: 0.7987 - val_loss: 0.4576
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4162 - val_accuracy: 0.8117 - val_loss: 0.4562
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4153 - val_accuracy: 0.8117 - val_loss: 0.4568
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4144 - val_accuracy: 0.8052 - val_loss: 0.4590
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4140 - val_accuracy: 0.8052 - val_loss: 0.4582
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4137 - val_accuracy: 0.8117 - val_loss: 0.4565
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4128 - val_accuracy: 0.7987 - val_loss: 0.4573
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4122 - val_accuracy: 0.8117 - val_loss: 0.4587
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4114 - val_accuracy: 0.8052 - val_loss: 0.4571
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4117 - val_accuracy: 0.8052 - val_loss: 0.4593
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4109 - val_accuracy: 0.8052 - val_loss: 0.4584
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4099 - val_accuracy: 0.8117 - val_loss: 0.4601
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4093 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4085 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4080 - val_accuracy: 0.8052 - val_loss: 0.4603
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4081 - val_accuracy: 0.8182 - val_loss: 0.4583
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4079 - val_accuracy: 0.8247 - val_loss: 0.4563
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4069 - val_accuracy: 0.8052 - val_loss: 0.4566
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4065 - val_accuracy: 0.8052 - val_loss: 0.4563
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4058 - val_accuracy: 0.8052 - val_loss: 0.4564
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4052 - val_accuracy: 0.8117 - val_loss: 0.4541
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4051 - val_accuracy: 0.8052 - val_loss: 0.4554
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4048 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4031 - val_accuracy: 0.7987 - val_loss: 0.4557
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4040 - val_accuracy: 0.8117 - val_loss: 0.4588
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4028 - val_accuracy: 0.8052 - val_loss: 0.4565
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4020 - val_accuracy: 0.8052 - val_loss: 0.4572
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4018 - val_accuracy: 0.8052 - val_loss: 0.4575
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8111 - loss: 0.4014 - val_accuracy: 0.8117 - val_loss: 0.4580
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.4018 - val_accuracy: 0.7987 - val_loss: 0.4552
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4015 - val_accuracy: 0.8052 - val_loss: 0.4557
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3995 - val_accuracy: 0.8052 - val_loss: 0.4544
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3996 - val_accuracy: 0.8117 - val_loss: 0.4570
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3995 - val_accuracy: 0.8117 - val_loss: 0.4549
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3980 - val_accuracy: 0.8182 - val_loss: 0.4581
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3990 - val_accuracy: 0.8117 - val_loss: 0.4605
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3976 - val_accuracy: 0.8247 - val_loss: 0.4563
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3968 - val_accuracy: 0.8117 - val_loss: 0.4566
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3963 - val_accuracy: 0.8117 - val_loss: 0.4521
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3964 - val_accuracy: 0.8117 - val_loss: 0.4524
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3964 - val_accuracy: 0.8117 - val_loss: 0.4534
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3956 - val_accuracy: 0.8117 - val_loss: 0.4527
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3950 - val_accuracy: 0.8117 - val_loss: 0.4536
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3944 - val_accuracy: 0.8182 - val_loss: 0.4554
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3945 - val_accuracy: 0.8117 - val_loss: 0.4551
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3930 - val_accuracy: 0.8052 - val_loss: 0.4536
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3935 - val_accuracy: 0.8117 - val_loss: 0.4564
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3928 - val_accuracy: 0.8117 - val_loss: 0.4564
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3916 - val_accuracy: 0.8117 - val_loss: 0.4575

# 3. no. of layers

In [31]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(112, activation='relu', input_dim=8))
  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model.add(Dense(112, activation='relu'))

  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [32]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory='mydir',
    project_name='number_of_layers'
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [33]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8051947951316833

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 11s

In [34]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4}

In [35]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [36]:
model.fit(x_train, y_train, batch_size=32, epochs=100, initial_epoch=5, validation_data=(x_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.7850 - loss: 0.4461 - val_accuracy: 0.7532 - val_loss: 0.5222
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4329 - val_accuracy: 0.7987 - val_loss: 0.4729
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4235 - val_accuracy: 0.7532 - val_loss: 0.5344
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4126 - val_accuracy: 0.7468 - val_loss: 0.5279
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4104 - val_accuracy: 0.7792 - val_loss: 0.4981
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8111 - loss: 0.3999 - val_accuracy: 0.7792 - val_loss: 0.5023
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8257 - loss: 0.3901 - val_accuracy: 0.7922 - val_loss: 0.4813
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8208 - loss: 0.3767 - val_accuracy: 0.8182 - val_loss: 0.4881
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8306 - loss: 0.3643 - val_accuracy: 0.7987 - val_loss: 0.4985
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8388 - loss: 0.3625 - val_accuracy: 0.7532 - val_loss: 0.5609
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8388 - loss: 0.3521 - val_accuracy: 0.7922 - val_loss: 0.5399
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8502 - loss: 0.3453 - val_accuracy: 0.7857 - val_loss: 0.5309
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8648 - loss: 0.3306 - val_accuracy: 0.7987 - val_loss: 0.5103
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8567 - loss: 0.3128 - val_accuracy: 0.7597 - val_loss: 0.5680
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8648 - loss: 0.3060 - val_accuracy: 0.7338 - val_loss: 0.6586
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.3022 - val_accuracy: 0.7662 - val_loss: 0.5758
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2689 - val_accuracy: 0.7792 - val_loss: 0.6511
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.2740 - val_accuracy: 0.7208 - val_loss: 0.7792
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2629 - val_accuracy: 0.7792 - val_loss: 0.7456
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9088 - loss: 0.2499 - val_accuracy: 0.7727 - val_loss: 0.6670
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2529 - val_accuracy: 0.7727 - val_loss: 0.6878
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9186 - loss: 0.2369 - val_accuracy: 0.7403 - val_loss: 0.7877
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9235 - loss: 0.2090 - val_accuracy: 0.7727 - val_loss: 0.7455
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9153 - loss: 0.2237 - val_accuracy: 0.7727 - val_loss: 0.7508
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9381 - loss: 0.1876 - val_accuracy: 0.7662 - val_loss: 0.7814
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9267 - loss: 0.1912 - val_accuracy: 0.7532 - val_loss: 0.8409
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9349 - loss: 0.1683 - val_accuracy: 0.7532 - val_loss: 1.0328
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9267 - loss: 0.1730 - val_accuracy: 0.7922 - val_loss: 0.9356
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9300 - loss: 0.1719 - val_accuracy: 0.7468 - val_loss: 0.9220
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9446 - loss: 0.1459 - val_accuracy: 0.7727 - val_loss: 1.0174
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9349 - loss: 0.1532 - val_accuracy: 0.7338 - val_loss: 0.9225
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9544 - loss: 0.1243 - val_accuracy: 0.7727 - val_loss: 0.9923
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9397 - loss: 0.1450 - val_accuracy: 0.7143 - val_loss: 1.2501
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9642 - loss: 0.1119 - val_accuracy: 0.6558 - val_loss: 1.1543
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9430 - loss: 0.1312 - val_accuracy: 0.7403 - val_loss: 1.0683
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9642 - loss: 0.0940 - val_accuracy: 0.7792 - val_loss: 1.1612
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.0981 - val_accuracy: 0.7338 - val_loss: 1.3179
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9577 - loss: 0.1149 - val_accuracy: 0.7532 - val_loss: 1.1722
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9707 - loss: 0.0827 - val_accuracy: 0.6818 - val_loss: 1.2785
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9560 - loss: 0.1052 - val_accuracy: 0.7403 - val_loss: 1.2786
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9707 - loss: 0.0783 - val_accuracy: 0.7143 - val_loss: 1.4113
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9821 - loss: 0.0656 - val_accuracy: 0.7273 - val_loss: 1.4026
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9691 - loss: 0.0792 - val_accuracy: 0.7013 - val_loss: 1.6343
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0589 - val_accuracy: 0.7403 - val_loss: 1.4264
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9772 - loss: 0.0625 - val_accuracy: 0.7403 - val_loss: 1.4898
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9691 - loss: 0.0831 - val_accuracy: 0.7532 - val_loss: 1.5816
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9739 - loss: 0.0514 - val_accuracy: 0.7078 - val_loss: 1.6873
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0429 - val_accuracy: 0.7143 - val_loss: 1.5533
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0530 - val_accuracy: 0.7338 - val_loss: 1.6989
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9739 - loss: 0.0650 - val_accuracy: 0.7078 - val_loss: 1.6390
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0598 - val_accuracy: 0.7273 - val_loss: 1.5900
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0339 - val_accuracy: 0.7403 - val_loss: 1.8537
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0453 - val_accuracy: 0.7208 - val_loss: 1.7191
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9674 - loss: 0.0836 - val_accuracy: 0.7013 - val_loss: 1.7939
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0239 - val_accuracy: 0.7532 - val_loss: 1.8044
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9837 - loss: 0.0477 - val_accuracy: 0.7338 - val_loss: 1.8296
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9772 - loss: 0.0795 - val_accuracy: 0.7273 - val_loss: 1.9459
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0265 - val_accuracy: 0.7403 - val_loss: 1.8234
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9756 - loss: 0.0680 - val_accuracy: 0.6883 - val_loss: 1.8751
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0292 - val_accuracy: 0.6883 - val_loss: 2.0809
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0428 - val_accuracy: 0.7338 - val_loss: 1.9015
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0270 - val_accuracy: 0.7338 - val_loss: 2.1820
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9772 - loss: 0.0598 - val_accuracy: 0.7078 - val_loss: 1.8719
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0293 - val_accuracy: 0.7338 - val_loss: 1.9819
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9967 - loss: 0.0126 - val_accuracy: 0.7143 - val_loss: 2.2482
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0376 - val_accuracy: 0.7208 - val_loss: 2.2372
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9902 - loss: 0.0211 - val_accuracy: 0.7013 - val_loss: 2.1453
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9821 - loss: 0.0470 - val_accuracy: 0.7532 - val_loss: 2.1422
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0232 - val_accuracy: 0.7403 - val_loss: 2.2144
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0490 - val_accuracy: 0.7078 - val_loss: 2.0155
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9886 - loss: 0.0265 - val_accuracy: 0.7532 - val_loss: 2.1783
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0093 - val_accuracy: 0.7273 - val_loss: 2.2528
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9984 - loss: 0.0068 - val_accuracy: 0.7403 - val_loss: 2.2948
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9788 - loss: 0.0745 - val_accuracy: 0.7338 - val_loss: 2.1739
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9967 - loss: 0.0087 - val_accuracy: 0.6883 - val_loss: 2.5610
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9853 - loss: 0.0536 - val_accuracy: 0.7143 - val_loss: 2.0987
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9967 - loss: 0.0084 - val_accuracy: 0.7078 - val_loss: 2.1551
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9967 - loss: 0.0126 - val_accuracy: 0.7078 - val_loss: 2.4488
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9902 - loss: 0.0177 - val_accuracy: 0.7403 - val_loss: 2.3480
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9984 - loss: 0.0047 - val_accuracy: 0.7143 - val_loss: 2.4686
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9935 - loss: 0.0280 - val_accuracy: 0.7078 - val_loss: 2.6106
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9902 - loss: 0.0365 - val_accuracy: 0.7143 - val_loss: 2.3916
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0164 - val_accuracy: 0.7208 - val_loss: 2.3607
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0206 - val_accuracy: 0.7273 - val_loss: 2.7456
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9853 - loss: 0.0814 - val_accuracy: 0.6753 - val_loss: 2.3599
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.6558 - val_loss: 2.5793
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0131 - val_accuracy: 0.6948 - val_loss: 2.4920
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0041 - val_accuracy: 0.6753 - val_loss: 2.4754
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0351 - val_accuracy: 0.7013 - val_loss: 2.6165
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0166 - val_accuracy: 0.7403 - val_loss: 2.6035
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9853 - loss: 0.0365 - val_accuracy: 0.6623 - val_loss: 2.7597
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0239 - val_accuracy: 0.7403 - val_loss: 2.2354
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.7208 - val_loss: 2.3164
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9984 - loss: 0.0075 - val_accuracy: 0.7078 - val_loss: 2.3729
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0388 - val_accuracy: 0.7078 - val_loss: 2.6516

# All Merged

In [45]:
def build_model(hp):
  model = Sequential()
  counter = 0
  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if counter == 0:
      model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=128, step=8), activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']), input_dim=8))
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
    else:
      model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=128, step=8), activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])))
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
    counter += 1

  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta']), loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [47]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials =3,
                        directory = "mydir",
                        project_name = "final_model_1")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [48]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.6363636255264282

Best val_accuracy So Far: 0.6428571343421936
Total elapsed time: 00h 00m 13s

In [49]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4,
 'units0': 8,
 'activation0': 'relu',
 'dropout0': 0.5,
 'optimizer': 'adam',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout2': 0.1,
 'units3': 8,
 'activation3': 'relu',
 'dropout3': 0.1}

In [50]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [51]:
model.fit(x_train, y_train, epochs=200, initial_epoch=5, validation_data=(x_test, y_test))

Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.6270 - loss: 0.7328 - val_accuracy: 0.6429 - val_loss: 0.6782
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6287 - loss: 0.6960 - val_accuracy: 0.6299 - val_loss: 0.6638
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6433 - loss: 0.6807 - val_accuracy: 0.6299 - val_loss: 0.6546
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6612 - loss: 0.6644 - val_accuracy: 0.6299 - val_loss: 0.6470
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6580 - loss: 0.6579 - val_accuracy: 0.6299 - val_loss: 0.6391
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6303 - loss: 0.6714 - val_accuracy: 0.6299 - val_loss: 0.6329
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6743 - loss: 0.6449 - val_accuracy: 0.6299 - val_loss: 0.6263
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6726 - loss: 0.6514 - val_accuracy: 0.6429 - val_loss: 0.6209
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6580 - loss: 0.6376 - val_accuracy: 0.6364 - val_loss: 0.6168
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6629 - loss: 0.6370 - val_accuracy: 0.6429 - val_loss: 0.6103
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6710 - loss: 0.6346 - val_accuracy: 0.6429 - val_loss: 0.6042
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.6129 - val_accuracy: 0.6558 - val_loss: 0.5967
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6873 - loss: 0.6205 - val_accuracy: 0.6623 - val_loss: 0.5914
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6661 - loss: 0.6211 - val_accuracy: 0.6688 - val_loss: 0.5883
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6694 - loss: 0.6274 - val_accuracy: 0.6818 - val_loss: 0.5848
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6726 - loss: 0.6117 - val_accuracy: 0.6753 - val_loss: 0.5806
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6661 - loss: 0.6178 - val_accuracy: 0.6753 - val_loss: 0.5778
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6857 - loss: 0.5951 - val_accuracy: 0.6883 - val_loss: 0.5727
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6954 - loss: 0.5936 - val_accuracy: 0.7013 - val_loss: 0.5654
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7101 - loss: 0.5809 - val_accuracy: 0.7208 - val_loss: 0.5555
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6922 - loss: 0.5917 - val_accuracy: 0.7338 - val_loss: 0.5493
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6808 - loss: 0.5919 - val_accuracy: 0.7338 - val_loss: 0.5488
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7101 - loss: 0.5833 - val_accuracy: 0.7273 - val_loss: 0.5485
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7199 - loss: 0.5859 - val_accuracy: 0.7338 - val_loss: 0.5465
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5647 - val_accuracy: 0.7338 - val_loss: 0.5456
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7296 - loss: 0.5559 - val_accuracy: 0.7403 - val_loss: 0.5398
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7003 - loss: 0.5811 - val_accuracy: 0.7338 - val_loss: 0.5389
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5483 - val_accuracy: 0.7532 - val_loss: 0.5341
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5678 - val_accuracy: 0.7597 - val_loss: 0.5318
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5641 - val_accuracy: 0.7597 - val_loss: 0.5283
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7085 - loss: 0.5639 - val_accuracy: 0.7662 - val_loss: 0.5246
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7345 - loss: 0.5542 - val_accuracy: 0.7662 - val_loss: 0.5225
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 0.5742 - val_accuracy: 0.7662 - val_loss: 0.5230
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6808 - loss: 0.5776 - val_accuracy: 0.7468 - val_loss: 0.5296
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.5452 - val_accuracy: 0.7532 - val_loss: 0.5266
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5577 - val_accuracy: 0.7597 - val_loss: 0.5248
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7231 - loss: 0.5525 - val_accuracy: 0.7662 - val_loss: 0.5218
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5321 - val_accuracy: 0.7662 - val_loss: 0.5185
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7117 - loss: 0.5665 - val_accuracy: 0.7597 - val_loss: 0.5234
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7134 - loss: 0.5508 - val_accuracy: 0.7662 - val_loss: 0.5203
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7117 - loss: 0.5622 - val_accuracy: 0.7857 - val_loss: 0.5211
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7117 - loss: 0.5647 - val_accuracy: 0.7857 - val_loss: 0.5234
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7215 - loss: 0.5548 - val_accuracy: 0.7597 - val_loss: 0.5218
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7313 - loss: 0.5378 - val_accuracy: 0.7792 - val_loss: 0.5197
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7134 - loss: 0.5493 - val_accuracy: 0.7792 - val_loss: 0.5195
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5373 - val_accuracy: 0.7792 - val_loss: 0.5185
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.5251 - val_accuracy: 0.7792 - val_loss: 0.5168
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5182 - val_accuracy: 0.7727 - val_loss: 0.5174
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5370 - val_accuracy: 0.7727 - val_loss: 0.5190
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5317 - val_accuracy: 0.7857 - val_loss: 0.5197
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5267 - val_accuracy: 0.7857 - val_loss: 0.5185
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5499 - val_accuracy: 0.7727 - val_loss: 0.5171
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5197 - val_accuracy: 0.7792 - val_loss: 0.5147
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5330 - val_accuracy: 0.7727 - val_loss: 0.5161
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5481 - val_accuracy: 0.7727 - val_loss: 0.5143
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.5032 - val_accuracy: 0.7792 - val_loss: 0.5126
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5181 - val_accuracy: 0.7857 - val_loss: 0.5138
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5177 - val_accuracy: 0.7792 - val_loss: 0.5131
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7296 - loss: 0.5206 - val_accuracy: 0.7792 - val_loss: 0.5147
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5282 - val_accuracy: 0.7792 - val_loss: 0.5157
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.5361 - val_accuracy: 0.7727 - val_loss: 0.5167
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5209 - val_accuracy: 0.7727 - val_loss: 0.5166
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4932 - val_accuracy: 0.7727 - val_loss: 0.5161
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5351 - val_accuracy: 0.7792 - val_loss: 0.5187
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.5124 - val_accuracy: 0.7662 - val_loss: 0.5185
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5120 - val_accuracy: 0.7727 - val_loss: 0.5168
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5139 - val_accuracy: 0.7727 - val_loss: 0.5173
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5062 - val_accuracy: 0.7792 - val_loss: 0.5233
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5259 - val_accuracy: 0.7727 - val_loss: 0.5243
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5396 - val_accuracy: 0.7662 - val_loss: 0.5244
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5199 - val_accuracy: 0.7792 - val_loss: 0.5225
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5094 - val_accuracy: 0.7792 - val_loss: 0.5211
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5118 - val_accuracy: 0.7792 - val_loss: 0.5217
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4938 - val_accuracy: 0.7727 - val_loss: 0.5189
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7182 - loss: 0.5213 - val_accuracy: 0.7792 - val_loss: 0.5194
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4958 - val_accuracy: 0.7792 - val_loss: 0.5175
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7313 - loss: 0.5318 - val_accuracy: 0.7662 - val_loss: 0.5183
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5119 - val_accuracy: 0.7662 - val_loss: 0.5185
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5014 - val_accuracy: 0.7662 - val_loss: 0.5174
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5184 - val_accuracy: 0.7662 - val_loss: 0.5188
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4892 - val_accuracy: 0.7662 - val_loss: 0.5162
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7590 - loss: 0.5004 - val_accuracy: 0.7857 - val_loss: 0.5122
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7459 - loss: 0.4940 - val_accuracy: 0.7727 - val_loss: 0.5135
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7655 - loss: 0.4978 - val_accuracy: 0.7857 - val_loss: 0.5117
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7329 - loss: 0.5106 - val_accuracy: 0.7922 - val_loss: 0.5118
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7378 - loss: 0.5166 - val_accuracy: 0.7922 - val_loss: 0.5106
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7362 - loss: 0.5040 - val_accuracy: 0.7727 - val_loss: 0.5121
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7280 - loss: 0.5108 - val_accuracy: 0.7662 - val_loss: 0.5172
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7394 - loss: 0.5270 - val_accuracy: 0.7662 - val_loss: 0.5208
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7313 - loss: 0.5299 - val_accuracy: 0.7727 - val_loss: 0.5224
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7313 - loss: 0.5203 - val_accuracy: 0.7403 - val_loss: 0.5305
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4941 - val_accuracy: 0.7792 - val_loss: 0.5278
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7313 - loss: 0.5004 - val_accuracy: 0.7727 - val_loss: 0.5248
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5032 - val_accuracy: 0.7727 - val_loss: 0.5247
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5038 - val_accuracy: 0.7727 - val_loss: 0.5242
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7476 - loss: 0.5087 - val_accuracy: 0.7662 - val_loss: 0.5226
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7524 - loss: 0.5052 - val_accuracy: 0.7597 - val_loss: 0.5218
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7280 - loss: 0.5158 - val_accuracy: 0.7597 - val_loss: 0.5212
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7508 - loss: 0.4834 - val_accuracy: 0.7727 - val_loss: 0.5223
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.5056 - val_accuracy: 0.7727 - val_loss: 0.5191
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4938 - val_accuracy: 0.7727 - val_loss: 0.5192
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7313 - loss: 0.5191 - val_accuracy: 0.7727 - val_loss: 0.5191
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5120 - val_accuracy: 0.7662 - val_loss: 0.5199
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4901 - val_accuracy: 0.7792 - val_loss: 0.5144
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4929 - val_accuracy: 0.7727 - val_loss: 0.5127
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5016 - val_accuracy: 0.7727 - val_loss: 0.5142
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.4906 - val_accuracy: 0.7662 - val_loss: 0.5144
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.4999 - val_accuracy: 0.7727 - val_loss: 0.5129
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.4990 - val_accuracy: 0.7662 - val_loss: 0.5176
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5004 - val_accuracy: 0.7662 - val_loss: 0.5159
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.5025 - val_accuracy: 0.7727 - val_loss: 0.5159
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5035 - val_accuracy: 0.7662 - val_loss: 0.5128
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4927 - val_accuracy: 0.7727 - val_loss: 0.5107
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.4980 - val_accuracy: 0.7727 - val_loss: 0.5097
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7231 - loss: 0.5165 - val_accuracy: 0.7727 - val_loss: 0.5100
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.5086 - val_accuracy: 0.7727 - val_loss: 0.5110
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.5002 - val_accuracy: 0.7792 - val_loss: 0.5127
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5137 - val_accuracy: 0.7727 - val_loss: 0.5157
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.4978 - val_accuracy: 0.7727 - val_loss: 0.5145
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7427 - loss: 0.5041 - val_accuracy: 0.7662 - val_loss: 0.5128
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7573 - loss: 0.4936 - val_accuracy: 0.7727 - val_loss: 0.5145
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.4960 - val_accuracy: 0.7792 - val_loss: 0.5112
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5014 - val_accuracy: 0.7727 - val_loss: 0.5083
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4937 - val_accuracy: 0.7727 - val_loss: 0.5084
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5064 - val_accuracy: 0.7727 - val_loss: 0.5101
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4905 - val_accuracy: 0.7727 - val_loss: 0.5109
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4934 - val_accuracy: 0.7662 - val_loss: 0.5095
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5001 - val_accuracy: 0.7662 - val_loss: 0.5083
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.4896 - val_accuracy: 0.7597 - val_loss: 0.5109
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7410 - loss: 0.4967 - val_accuracy: 0.7532 - val_loss: 0.5134
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5175 - val_accuracy: 0.7597 - val_loss: 0.5142
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.4957 - val_accuracy: 0.7597 - val_loss: 0.5121
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5148 - val_accuracy: 0.7597 - val_loss: 0.5109
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.4931 - val_accuracy: 0.7597 - val_loss: 0.5124
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4973 - val_accuracy: 0.7662 - val_loss: 0.5138
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7215 - loss: 0.5136 - val_accuracy: 0.7662 - val_loss: 0.5136
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5119 - val_accuracy: 0.7662 - val_loss: 0.5163
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4809 - val_accuracy: 0.7727 - val_loss: 0.5143
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5207 - val_accuracy: 0.7727 - val_loss: 0.5128
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7476 - loss: 0.5002 - val_accuracy: 0.7727 - val_loss: 0.5137
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7508 - loss: 0.4903 - val_accuracy: 0.7727 - val_loss: 0.5103
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7557 - loss: 0.4924 - val_accuracy: 0.7662 - val_loss: 0.5094
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7508 - loss: 0.5040 - val_accuracy: 0.7727 - val_loss: 0.5102
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7476 - loss: 0.4932 - val_accuracy: 0.7597 - val_loss: 0.5079
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7606 - loss: 0.4677 - val_accuracy: 0.7662 - val_loss: 0.5078
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7573 - loss: 0.4898 - val_accuracy: 0.7727 - val_loss: 0.5062
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7638 - loss: 0.4754 - val_accuracy: 0.7727 - val_loss: 0.5068
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7524 - loss: 0.4872 - val_accuracy: 0.7662 - val_loss: 0.5065
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7459 - loss: 0.5095 - val_accuracy: 0.7727 - val_loss: 0.5076
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5043 - val_accuracy: 0.7792 - val_loss: 0.5070
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5038 - val_accuracy: 0.7792 - val_loss: 0.5061
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.5091 - val_accuracy: 0.7792 - val_loss: 0.5057
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.4889 - val_accuracy: 0.7792 - val_loss: 0.5116
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.5110 - val_accuracy: 0.7727 - val_loss: 0.5113
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7687 - loss: 0.4930 - val_accuracy: 0.7727 - val_loss: 0.5093
Epoch 161/200